FROM ghcr.io/defiance-project/bake-defiance:latest

COPY . .

RUN apt-get update && apt-get remove -y git-lfs && make download && make clean && make bootstrap && apt-get install -y git-lfs && rm -rf /var/lib/apt/lists/*

WORKDIR $NS3_HOME

# set to 'True' to build ns3 and ns3-defiance
ARG BUILD_NS3=

RUN if [ "$BUILD_NS3" = "True" ]; then ./ns3 build; fi
