FROM ghcr.io/defiance-project/bake-defiance:latest

COPY . .

ADD https://api.github.com/repos/DEFIANCE-project/ns3-DEFIANCE/commits?per_page=1 ns3-defiance-latest-commit.json
ADD https://api.github.com/repos/DEFIANCE-project/ns3-ai/commits?per_page=1 ns3-ai-latest-commit.json
RUN apt-get remove -y git-lfs && make download && make clean && make bootstrap && apt-get install -y git-lfs

WORKDIR $NS3_HOME

# set to 'True' to build ns3 and ns3-defiance
ARG BUILD_NS3=

RUN if [ "$BUILD_NS3" = "True" ]; then ./ns3 build; fi
