FROM ubuntu:jammy

RUN apt-get update && apt-get -y install python3-pip python3-venv python-is-python3 libgl1-mesa-glx libglib2.0-0 libprotobuf23 libxml2 && pip install poetry

ENV POETRY_VIRTUALENVS_IN_PROJECT=true

COPY source/*/contrib/defiance/pyproject.toml source/*/contrib/defiance/poetry* /defiance/
RUN cd defiance && poetry install --no-root --without local

ENV VIRTUAL_ENV=/defiance/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY source/ns-3.40/build /build

COPY source/ns-3.40/contrib/defiance defiance
COPY source/*/contrib/ai ai
RUN cd defiance && poetry install

# copy and activate built ns3
COPY source/*/build build
ENV LD_LIBRARY_PATH="/build/lib"
ENV NS3_HOME=/

WORKDIR /build
