FROM ubuntu:jammy AS venv-builder

RUN apt-get update && apt-get -y install python3-pip python3-venv python-is-python3 libgl1-mesa-glx libglib2.0-0 libprotobuf23 libxml2 && pip install poetry

COPY source/*/contrib/ai ai
COPY source/*/contrib/defiance defiance

# bundle ns-defiance into venv
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
RUN cd defiance && poetry install
ENV VIRTUAL_ENV=/defiance/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN pip install -e /ai/model/gym-interface/py/

# copy and activate built ns3
COPY source/*/build build
ENV LD_LIBRARY_PATH="/build/lib"
ENV NS3_HOME=/

WORKDIR /build
